# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server
# process.
#
# Site settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
      related_order: 9999

# Build settings
source: src
sass:
  implementation: sass-embedded
  load_paths:
    - ../node_modules/*

plugins:
  - jekyll-redirect-from
